// Centralized product data for the entire site
export const candlesData = [
  {
    id: "floral-essence",
    name: "Floral Essence",
    description: "Delicate blooms and fresh petals create a garden sanctuary",
    fullDescription:
      "Immerse yourself in a blooming garden with our Floral Essence candle. This sophisticated blend combines delicate rose petals, fresh jasmine, and subtle hints of lily to create an enchanting atmosphere. Hand-poured with premium soy wax and infused with natural essential oils, this candle burns cleanly for up to 60 hours.",
    price: 42,
    image: "/luxury-floral-candle-pink-roses.jpg",
    category: "Floral",
    badge: "Best Seller",
    collection: "Signature Collection",
    images: [
      "/luxury-floral-candle-pink-roses.jpg",
      "/floral-candle-lifestyle-1.jpg",
      "/floral-candle-lifestyle-2.jpg",
      "/floral-candle-detail-1.jpg",
      "/floral-candle-detail-2.jpg",
    ],
    sizes: [
      { size: "8oz", price: 28, burnTime: "45-50 hours" },
      { size: "14oz", price: 45, burnTime: "80-90 hours" },
      { size: "3-Wick", price: 65, burnTime: "120-130 hours" },
    ],
    colors: [
      { name: "Blush Pink", hex: "#f2c0ca" },
      { name: "Cream", hex: "#FFF8F6" },
      { name: "White", hex: "#FFFFFF" },
    ],
    stockStatus: "In Stock",
    rating: 4.9,
    reviewCount: 127,
    scentInspiration:
      "Inspired by morning walks through blooming rose gardens, where dewdrops glisten on petals and the air is filled with nature's most delicate perfume.",
    ingredients: ["Soy Wax", "Rose Essential Oil", "Jasmine Fragrance", "Lily Extract", "Cotton Wick"],
    scentNotes: {
      top: "Fresh Rose Petals, Bergamot",
      middle: "Jasmine, Lily, Peony",
      base: "Soft Musk, White Woods",
    },
    specifications: {
      burnTime: "80-90 hours",
      waxType: "100% Soy Wax",
      wickType: "Cotton Wick",
      weight: "14oz / 400g",
      dimensions: '3.2" x 3.5"',
      refillable: "Yes",
      ecoFriendly: true,
    },
    careInstructions:
      "For best results, trim wick to 1/4 inch before each use. Allow wax to melt to the edges on first burn (2-3 hours). Never burn for more than 4 hours at a time. Keep away from drafts and flammable materials.",
    features: [
      "Hand-poured with care",
      "100% Natural Ingredients",
      "Clean-burning cotton wick",
      "Eco-friendly packaging",
      "Gift-ready presentation",
      "Vegan & Cruelty-free",
    ],
  },
  {
    id: "woodland-retreat",
    name: "Woodland Retreat",
    description: "Earthy cedar and warm amber evoke forest tranquility",
    fullDescription:
      "Escape to a serene forest with our Woodland Retreat candle. Rich cedarwood mingles with warm amber and subtle pine notes to transport you to a peaceful woodland sanctuary. Perfect for creating a cozy, grounding atmosphere in any space.",
    price: 45,
    image: "/luxury-wooden-candle-forest-scent.jpg",
    category: "Woody",
    collection: "Nature's Embrace",
    images: [
      "/luxury-wooden-candle-forest-scent.jpg",
      "/woodland-candle-lifestyle-1.jpg",
      "/woodland-candle-lifestyle-2.jpg",
      "/woodland-candle-detail-1.jpg",
      "/woodland-candle-detail-2.jpg",
    ],
    sizes: [
      { size: "8oz", price: 30, burnTime: "45-50 hours" },
      { size: "14oz", price: 48, burnTime: "80-90 hours" },
      { size: "3-Wick", price: 68, burnTime: "120-130 hours" },
    ],
    colors: [
      { name: "Natural Wood", hex: "#8B7355" },
      { name: "Forest Green", hex: "#2F4F4F" },
    ],
    stockStatus: "In Stock",
    rating: 4.8,
    reviewCount: 98,
    scentInspiration:
      "Capturing the essence of a quiet forest retreat, where ancient trees whisper stories and the earth beneath your feet grounds your spirit.",
    ingredients: ["Soy Wax", "Cedarwood Oil", "Amber Resin", "Pine Extract", "Wooden Wick"],
    scentNotes: {
      top: "Fresh Pine, Eucalyptus",
      middle: "Cedarwood, Sandalwood",
      base: "Warm Amber, Moss",
    },
    specifications: {
      burnTime: "80-90 hours",
      waxType: "100% Soy Wax",
      wickType: "Wooden Wick",
      weight: "14oz / 400g",
      dimensions: '3.2" x 3.5"',
      refillable: "Yes",
      ecoFriendly: true,
    },
    careInstructions:
      "Trim wooden wick to 1/8 inch before each use. Allow wax to melt to edges on first burn. The wooden wick creates a gentle crackling sound for added ambiance.",
    features: [
      "Hand-poured with care",
      "Crackling wooden wick",
      "100% Natural Ingredients",
      "Eco-friendly packaging",
      "Gift-ready presentation",
      "Vegan & Cruelty-free",
    ],
  },
  {
    id: "citrus-bliss",
    name: "Citrus Bliss",
    description: "Bright bergamot and sweet orange energize your space",
    fullDescription:
      "Invigorate your senses with our Citrus Bliss candle. A vibrant blend of bergamot, sweet orange, and zesty lemon creates an uplifting and energizing atmosphere. Perfect for morning rituals or brightening any room with fresh, clean fragrance.",
    price: 38,
    image: "/luxury-citrus-candle-orange-lemon.jpg",
    category: "Fresh",
    badge: "New Arrival",
    collection: "Energize Collection",
    images: [
      "/luxury-citrus-candle-orange-lemon.jpg",
      "/citrus-candle-lifestyle-1.jpg",
      "/citrus-candle-lifestyle-2.jpg",
      "/citrus-candle-detail-1.jpg",
      "/citrus-candle-detail-2.jpg",
    ],
    sizes: [
      { size: "8oz", price: 26, burnTime: "40-45 hours" },
      { size: "14oz", price: 42, burnTime: "75-85 hours" },
      { size: "3-Wick", price: 62, burnTime: "110-120 hours" },
    ],
    colors: [
      { name: "Sunshine Yellow", hex: "#FFD700" },
      { name: "Cream", hex: "#FFF8F6" },
    ],
    stockStatus: "Low Stock",
    rating: 4.9,
    reviewCount: 156,
    scentInspiration:
      "Inspired by sun-drenched citrus groves where golden fruits hang heavy on branches and the air sparkles with vibrant, uplifting energy.",
    ingredients: ["Soy Wax", "Bergamot Oil", "Orange Extract", "Lemon Zest", "Cotton Wick"],
    scentNotes: {
      top: "Bergamot, Lemon Zest",
      middle: "Sweet Orange, Grapefruit",
      base: "Light Musk, Vanilla",
    },
    specifications: {
      burnTime: "75-85 hours",
      waxType: "100% Soy Wax",
      wickType: "Cotton Wick",
      weight: "14oz / 400g",
      dimensions: '3.2" x 3.5"',
      refillable: "Yes",
      ecoFriendly: true,
    },
    careInstructions:
      "Trim wick to 1/4 inch before lighting. Burn until wax melts to edges. Perfect for morning energy or afternoon pick-meup.",
    features: [
      "Hand-poured with care",
      "Energizing citrus blend",
      "100% Natural Ingredients",
      "Eco-friendly packaging",
      "Gift-ready presentation",
      "Vegan & Cruelty-free",
    ],
  },
  {
    id: "vanilla-dreams",
    name: "Vanilla Dreams",
    description: "Rich vanilla and creamy tonka bean for ultimate comfort",
    fullDescription:
      "Indulge in pure comfort with our Vanilla Dreams candle. This luxurious blend features rich Madagascar vanilla, creamy tonka bean, and subtle caramel notes. The perfect candle for creating a warm, inviting atmosphere that feels like a cozy embrace.",
    price: 40,
    image: "/luxury-vanilla-candle-cream-aesthetic.jpg",
    category: "Gourmand",
    collection: "Comfort Collection",
    images: [
      "/luxury-vanilla-candle-cream-aesthetic.jpg",
      "/vanilla-candle-lifestyle-1.jpg",
      "/vanilla-candle-lifestyle-2.jpg",
      "/vanilla-candle-detail-1.jpg",
      "/vanilla-candle-detail-2.jpg",
    ],
    sizes: [
      { size: "8oz", price: 28, burnTime: "45-50 hours" },
      { size: "14oz", price: 44, burnTime: "80-90 hours" },
      { size: "3-Wick", price: 64, burnTime: "120-130 hours" },
    ],
    colors: [
      { name: "Cream", hex: "#FFF8F6" },
      { name: "Caramel", hex: "#D2691E" },
    ],
    stockStatus: "In Stock",
    rating: 5.0,
    reviewCount: 203,
    scentInspiration:
      "Reminiscent of grandmother's kitchen, where vanilla beans steep in warm cream and the promise of sweet comfort fills every corner.",
    ingredients: ["Soy Wax", "Vanilla Bean Extract", "Tonka Bean", "Caramel Notes", "Cotton Wick"],
    scentNotes: {
      top: "Sweet Cream, Sugar",
      middle: "Madagascar Vanilla, Tonka Bean",
      base: "Caramel, Warm Musk",
    },
    specifications: {
      burnTime: "80-90 hours",
      waxType: "100% Soy Wax",
      wickType: "Cotton Wick",
      weight: "14oz / 400g",
      dimensions: '3.2" x 3.5"',
      refillable: "Yes",
      ecoFriendly: true,
    },
    careInstructions:
      "Trim wick before each use. Perfect for evening relaxation and creating a cozy atmosphere. Pairs beautifully with reading or meditation.",
    features: [
      "Hand-poured with care",
      "Madagascar vanilla beans",
      "100% Natural Ingredients",
      "Eco-friendly packaging",
      "Gift-ready presentation",
      "Vegan & Cruelty-free",
    ],
  },
]

export const coursesData = [
  {
    id: "candle-basics",
    title: "Candle Making Basics",
    description: "Learn the fundamentals of candle making, from selecting wax to perfecting your pour technique",
    fullDescription:
      "This comprehensive beginner course covers everything you need to start your candle-making journey. Learn about different wax types, wick selection, fragrance blending, and proper pouring techniques. By the end of this course, you'll have created your own collection of beautiful candles.",
    level: "Beginner",
    duration: "4 weeks",
    price: 299,
    students: 1250,
    image: "/candle-making-process-hands-pouring.jpg",
    syllabus: [
      "Week 1: Introduction to Candle Making & Materials",
      "Week 2: Wax Selection & Melting Techniques",
      "Week 3: Fragrance Blending & Wick Selection",
      "Week 4: Pouring, Finishing & Troubleshooting",
    ],
    includes: ["4 Live Sessions", "Course Materials Kit", "Lifetime Access", "Certificate of Completion"],
  },
]
